name: app_contact
description: Sebuah Flutter app manajemen kontak anda

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.4+4
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/default_avatar.png
    - assets/user_profile.png

  uses-material-design: true
